// src/components/Button/Button.jsx
import React, { useCallback } from 'react';
import PropTypes from 'prop-types';
import colors from '../../theme/colors.scss';
import { SoftKeyConsumer } from '../SoftKey/withSoftKeyManager';
import { useFocus } from '../../hooks';
import './Button.scss';

const prefixCls = 'kai-button';

const Button = React.memo(props => {
  const {
    text,
    icon,
    iconSrc,
    iconSide,
    onClick,
    focusColor,
    form,
    formAction,
    formEncType,
    formMethod,
    formNoValidate,
    formTarget,
    name,
    type,
    onFocusChange,
    index,
    forwardedRef,
    softKeyManager,
    softKeyText,
    softKeyIcon,
  } = props;

  const handleFocusChange = useCallback(
    isNowFocused => {
      if (isNowFocused) {
        if (softKeyIcon != null) {
          softKeyManager.setCenterIcon(softKeyIcon);
        } else {
          softKeyManager.setSoftKeyTexts({ centerText: softKeyText });
        }

        softKeyManager.setSoftKeyCallbacks({
          centerCallback: onClick,
        });
        onFocusChange(index);
      } else {
        softKeyManager.unregisterSoftKeys();
      }
    },
    [index, onFocusChange, onClick, softKeyManager, softKeyText, softKeyIcon]
  );

  const isFocused = useFocus(forwardedRef, handleFocusChange, false);

  const buttonCls = prefixCls;
  const inputCls = `${prefixCls}-input`;
  const lineCls = `${prefixCls}-line ${
    iconSide === 'left' ? 'right' : iconSide === 'right' ? 'left' : ''
  }`;
  const textCls = `${prefixCls}-text`;
  const iconCls = `${prefixCls}-icon-${isFocused ? 'focused' : 'unfocused'}`;

  const renderedIcon = iconSrc === null ?
    <span className={icon} /> :
    <img src={iconSrc} alt="" />;

  const iconComp = (
    <div className={ iconCls}>
      {renderedIcon}
    </div>
  );

  return (
    <div className={buttonCls}>
      <button
        tabIndex="0"
        className={inputCls}
        style={{ backgroundColor: isFocused ? focusColor : colors.grayscale20 }}
        form={form}
        formAction={formAction}
        formEncType={formEncType}
        formMethod={formMethod}
        formNoValidate={formNoValidate}
        formTarget={formTarget}
        name={name}
        type={type}
        ref={forwardedRef}
        onClick={onClick}
        onFocus={() => handleFocusChange(true)}
        onBlur={() => handleFocusChange(false)}
      >
        {iconSide === 'left' ? iconComp : null}
        <div className={lineCls}>
          <span className={textCls}>{text}</span>
        </div>
        {iconSide === 'right' ? iconComp : null}
      </button>
    </div>
  );
});

Button.propTypes = {
  text: PropTypes.string.isRequired,
  icon: PropTypes.string,
  iconSrc: PropTypes.string,
  onClick: PropTypes.func.isRequired,
  iconSide: PropTypes.oneOf(['left', 'right']),
  focusColor: PropTypes.string,
  // HTML Button props
  form: PropTypes.string,
  formAction: PropTypes.string,
  formEncType: PropTypes.oneOf([
    'application/x-www-form-urlencoded',
    'multipart/form-data',
    'text/plain',
  ]),
  formMethod: PropTypes.oneOf(['get', 'post']),
  formNoValidate: PropTypes.bool,
  formTarget: PropTypes.oneOf(['_blank', '_self', '_parent', '_top']),
  name: PropTypes.string,
  type: PropTypes.oneOf(['button', 'reset', 'submit']),
  // For ListView navigation
  onFocusChange: PropTypes.func,
  index: PropTypes.number,
  forwardedRef: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.shape({ current: PropTypes.instanceOf(Element) }),
  ]),
  // For softkey
  softKeyText: PropTypes.string,
  softKeyIcon: PropTypes.string,
};

Button.defaultProps = {
  icon: null,
  iconSrc: null,
  iconSide: null,
  focusColor: colors.defaultFocusColor,
  type: 'button',
  form: undefined,
  formAction: undefined,
  formEncType: undefined,
  formMethod: undefined,
  formNoValidate: undefined,
  formTarget: undefined,
  name: undefined,
  softKeyText: 'select',
  softKeyIcon: null,
};

export default React.forwardRef((props, ref) => (
  <SoftKeyConsumer>
    {context => (
      <Button softKeyManager={context} forwardedRef={ref} {...props} />
    )}
  </SoftKeyConsumer>
));

// src/components/Button/Button.vue
<template>
    <!--iconComp-->
    
    <!--iconComp-->
    <div :class="buttonCls">
        <button
            tabindex="0"
            :class="inputCls"
            :style="style"
            :form="form"
            :formAction="formAction"
            :formEncType="formEncType"
            :formMethod="formMethod"
            :formNoValidate="formNoValidate"
            :formTarget="formTarget"
            :name="name"
            :type="type"
            :ref="ref"
            :onClick="onClick"
            :onFocus="onFocus"
            :onBlur="onBlur"
        >
            {{ iconSide === 'left' ? iconComp: null}}
            <div :class="lineCls">
                <span :class="textCls">{{ text }}</span>
            </div>
            {{ iconSide === 'right' ? iconComp: null}}
        </button>
    </div>
</template>
<script>
    import colors from '../../themes/colors.scss'
    const prefixCls = 'kai-button';
    const isFocused;

    export default {
        name: "Button",
        props: {
            text: {
                type: String
            },
            icon: {
                type: String
            },
            iconSrc: {
                type: String
            },
            onClick: {
                type: Function
            },
            iconSide: {
                validator (value) {
                    return oneOf(value, ['left', 'right'])
                }
            },
            focusColor: {
                type: String,
                default: colors.defaultFocusColor
            },
            form: {
                type: String
            },
            formAction: {
                type: String
            },
            formEncType: {
                validator (value) {
                    return oneOf(value, ['application/x-www-form-urlencoded', 'multipart/form-data', 'text/plain',])
                }
            },
            formMethod: {
                validator (value) {
                    return oneOf(value, ['get', 'post'])
                }
            },
            formNoValidate: {
                type: Boolean
            },
            formTarget: {
                validator (value) {
                    return oneOf(value, ['_blank', '_self', '_parent', '_top'])
                }
            },
            name: {
                type: String
            },
            type: {
                validator (value) {
                    return oneOf(value, ['button', 'reset', 'submit'])
                },
                default: 'button'
            },
            onFocusChange: {
                type: Function
            },
            index: {
                type: Number
            },
            softKeyText: {
                type: String,
                default: 'select'
            },
            softKeyIcon: {
                type: String
            }
        },
        data() {
            return {
                prefixCls = prefixCls
            };
        },
        computed: {
            buttonCls () {
                return `${prefixCls}`;
            },
            inputCls () {
                return `${prefixCls}-input`;
            },
            lineCls () {
                return `${prefixCls}-line ${
                    iconSide === 'left' ? 'right' : iconSide === 'right' ? 'left' : ''
                }`;
            },
            textCls () {
                return `${prefixCls}-text`;
            },
            iconCls () {
                return `${prefixCls}-icon-${isFocused ? 'focus' : 'unfocused'}`;
            },
            iconComp () {
                return `<div :class="iconCls">
                        <span :class="icon"></span>
                        <img :src="iconSrc" alt="" />
                    </div>`;
            }
        }
    }
</script>
