// src/components/ArrowListItem.vue
<template>
	<div
		tabIndex="0"
		:class="wrapClasses"
		:ref="forwardedRef"
		:style="style"
		@focus="focus"
		@blur="unFocus"
	>
		<div :class="lineClasses">
			<span :class="primaryClasses">{{ primary }}</span>
			<label :class="secondaryClasses">{{ secondary }}</label>
		</div>
		<div :class="iconClasses">
			<span class="kai-icon-arrow"></span>
		</div>
	</div>
</template>
<script>
    import colors from '!!../utils/less-loader!../themes/colors.less';

    const prefixCls = 'kai-al';

    export default {
        name: 'ArrowListItem',
        props: {
            primary: {
                type: String
            },
            secondary: {
                type: String
            },
            focusColor: {
                type: String,
                default: colors['defaultFocusColor']
            },
            forwardedRef: String
        },
        data() {
            return {
                isFocused: false,
                prefixCls: prefixCls
            };
        },
        computed: {
            style() {
                return {
                    backgroundColor: this.isFocused ? this.focusColor : null
								}
            },
            wrapClasses() {
                return `${prefixCls}`;
            },
            lineClasses() {
                return `${prefixCls}-line`;
            },
            iconClasses() {
                return `${prefixCls}-icon-${this.isFocused ? 'focused' : 'unfocused'}`;
            },
            primaryClasses() {
                return `${prefixCls}-primary`;
            },
            secondaryClasses() {
                return `${prefixCls}-secondary`;
            }
        },
        methods: {
            focus() {
                this.isFocused = true;
            },
            unFocus() {
                this.isFocused = false;
            }
        }
    }
</script>

<style lang="less">
	@import '../styles/ArrowListItem.less';
</style>

// src/components/ArrowListItem/ArrowListItem.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { useFocus } from '../../hooks';
import colors from '../themes/colors.scss'

import './ArrowListItem.scss';

const prefixCls = 'kai-al';

const ArrowListItem = React.memo(
  props => {
    const {
      primary,
      secondary,
      focusColor,
      forwardedRef,
      index,
      onFocusChange
    } = props;

    const handleFocusChange = isNowFocused => {
      if (isNowFocused) {
        onFocusChange(index);
      }
    }

    const isFocused = useFocus(forwardedRef, handleFocusChange, false);

    const itemCls = prefixCls;
    const iconCls = `${prefixCls}-icon-${isFocused ? 'focused' : 'unfocused'}`;
    const lineCls = `${prefixCls}-line`;
    const primaryCls = `${prefixCls}-primary`;
    const secondaryCls = `${prefixCls}-secondary ${secondary ? '' : 'hidden'}`;

    return (
      <div
        tabIndex="0"
        className={itemCls}
        style={{ backgroundColor: isFocused ? focusColor : colors.white }}
        ref={forwardedRef}
      >
        <div className={lineCls}>
          <span className={primaryCls}>{primary}</span>
          <label className={secondaryCls}>{secondary}</label>
        </div>
        <div className={iconCls}>
          <span className="kai-icon-arrow" />
        </div>
      </div>
    );
  }
);

ArrowListItem.propTypes = {
  primary: PropTypes.string.isRequired,
  secondary: PropTypes.string,
  focusColor: PropTypes.string,
  forwardedRef: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.shape({ current: PropTypes.instanceOf(Element) }),
  ]),
  index: PropTypes.number,
  onFocusChange: PropTypes.func,
};

ArrowListItem.defaultProps = {
  secondary: null,
  focusColor: colors.defaultFocusColor,
};

export default React.forwardRef((props, ref) => (
  <ArrowListItem forwardedRef={ref} {...props} />
));
